### ISSUE TITLE
Warning: failed to stat (file)

### ISSUE THREAD

**Issue by johnjelinek** [broccolijs/broccoli#154]
In emacs, whenever I modify a file, the console floods with messages like: `Warning: failed to stat src/html/.#index.html`. What is the best way to ignore these files so it doesn't flood?

**Comment by dtkirsch** [comment]
+1 to the idea of an ignore file.  How is this still an issue more than a year after the issue was opened and a viable solution was proposed?  Ember is one of many software platforms I use, and Emacs works flawlessly with all the others.  I'm not about to switch development editors just because Broccoli isn't playing nice.

**Comment by darshanime** [comment]
Is there any update on the `.brocignore` file? @joliss

**Comment by stefanpenner** [comment]
Interestingly, I am not able to reproduce this problem any longer.

1. create broken symlink in the input of a broccoli pipeline consumed by `new Funnel`
2. let broccoli rebuild
3. all is well, no warnings etc.

It is possible we absorb this issue in one of the various libraries that actually do  the file reading..

---

It is possible my concise reproduction was no sufficient, if so. Please provide another and I will gladly reopen.

**Comment by MorayJ** [comment]
I'm still getting an issue that seems to be this...

**ember-cli: 3.0.2
node: 8.1.3
os: linux x64**
```
ENOENT: no such file or directory, unlink `'/whatever/whatever/whatever/tmp/funnel-output_path-i8WfoqFw.tmp/templates/.#application.hbs'`


Stack Trace and Error Report: /tmp/error.dump.4d26fb32070fdda70dce992ff512d001.log
```
