### ISSUE TITLE
broccoli build command should fail-fast if outputDir already exists

### ISSUE THREAD

**Issue by naartjie** [broccolijs/broccoli#217]
If the `<target>` dir already exists, `broccoli build` should fail with an error message before doing the build first.

**Comment by joliss** [comment]
I don't want a `--force` option in Broccoli itself - see [this comment](https://github.com/broccolijs/broccoli/pull/225#issuecomment-84625203).

Failing faster would be nice, but it would complicate the code. At the moment, I'd prefer to just live with the slowness, because it's pretty rare. Maybe we'll fix it in the future.

**Comment by joliss** [comment]
Hm actually, failing fast *is* a good idea. I landed this in 073fed404e2e1105588f0f795815ae39c331da5d. Thanks!

**Comment by naartjie** [comment]
:+1:  thanks @joliss
