### ISSUE TITLE
Plugin API a Bit Confusing

### ISSUE THREAD

**Issue by mikehaas763** [broccolijs/broccoli#266]
> By convention, plugins will export a function that takes one or more input trees, and returns an output  tree object. Usually your plugin will be implemented as a class representing a tree, but it is recommended to make the new operator optional (example).

I believe Broccoli walks the tree using regular function calls. Which means that if you have any kind of state being managed in the plugin class that it's not "recommended to make the new operator optional" but is actually required. Does that sound right?

I'm finding the API for plugins a bit unusual. If others feel the same then maybe we could come up with something better. What's unusual for me is that the plugin api is just a function while typically being implemented as a class. I personally like using class constructs to manage state but then the optional new operator that is practically mandatory makes it weird. I know that condition is occasionally used in libs to prevent errors if the consumer forgets to use `new`.

One example of where this could be a problem is with ES6 classes. You can't invoke an ES6 class even though it's just syntactic sugar for a regular constructor function. You could just use functions and capture state with a closure, which I'm not really a fan of. You could even go as far as not allowing state and just using pure functions but I doubt that's feasible and I think that the state enables a nice and intuitive API.

It also seems like the plugin object and the tree object are a hybrid (at least with the cache-writer plugin), is that correct? Why not just define a plugin object interface and a tree object interface and allow any plugin creators to implement those interfaces as objects however they want to?

Am I just completely missing the point? I'm not an idiot (or at least not completely :smile:) so I stand by it being a bit confusing and so at least could maybe use some more documentation.

**Comment by mikehaas763** [comment]
To clarify I'm not saying that the current plugin API doesn't make it easy to write plugins if you just follow the recommended way (I've looked at the source for probably a dozen plugins). Jus that I think it could be improved.

**Comment by joliss** [comment]
ES6 classes not supporting new-less instantiation is indeed a problem, and we might switch to favoring `new` over newless because of this.

Work on a new API is actively in progress - there's consensus that the current API is not the nicest to implement against.

> It also seems like the plugin object and the tree object are a hybrid (at least with the cache-writer plugin), is that correct? Why not just define a plugin object interface and a tree object interface and allow any plugin creators to implement those interfaces as objects however they want to?

I'm not sure I understand what you're suggesting... With current terminology, a *tree* simply means a *plugin instance* or a *string* (referring to a file system path). In terms of separating interfaces, do you want to elaborate on what you had in mind?

**Comment by stefanpenner** [comment]
This issue seems to have gone stale, many improvements and changes have occured.

1. we use ES Classes now
2. Plugins can use `this.input` https://github.com/broccolijs/broccoli-plugin#pluginprototypeinput and `this.output` to read and write https://github.com/broccolijs/broccoli-plugin#pluginprototypeoutput
3. the above lays a good foundation for future steps to simplify and set plugins authors up for success.
