### ISSUE TITLE
ENOTEMPTY tree_merger-temp_dest_dir on almost every compile, not making symlinks, 30 sec build time on Windows

### ISSUE THREAD

**Issue by blisst** [broccolijs/broccoli#269]
This is a follow-up to: https://github.com/ember-cli/ember-cli/issues/4375 and https://github.com/broccolijs/broccoli/issues/232  

I keep getting `ENOTEMPTY tree_merger-temp_dest_dir` errors on almost every compile, 30 sec build time on:
Windows 7
ember-cli 0.2.7
node 0.12.2

The error references `rmkidsSync` at `rmdirSync` in `ember-cli\node_modules\quick-temp\node_modules\rimraf\rimraf.js`.  I am not sure how to get the actual error output.

I have taken all the precautions related to getting rid of Broccoli compilation errors:
--no Sublime Text `tmp` monitoring
--ember-cli-windows
--antivirus not scanning folders
--Windows Defender, Windows search disabled in those folders
--only one CMD window open to my project root at a time
--reinitialized project (removed `tmp`,`node_modules`,`bower_components`, reinstalled everything according to Ember-CLI upgrade procedure

However, I still get `ENOTEMPTY tree_merger-temp_dest_dir...` errors every time, and compilation of my app takes 30 seconds.  

One answer I might have is that, while `mklink` works find for making symlinks in an Admin window for me, npm's `can-symlink` says that I am unable to make symlinks.  Could this be related?

**Comment by stefanpenner** [comment]
Although not perfect, we have greatly improved windows performance. We have not reach a perfect state, but has improved since 2015. Also since then windows folks have made it possible for developers to utilize symlinks: https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/ 

the linked issue has also been closed: https://github.com/ember-cli/ember-cli/issues/4375#issuecomment-166503798

I am also going to close this one.

For future windows related performance issues:

1. hard-errors should be reported (although ideally on the plugin they originated from)
2. performance issues, please be sure you are using windows provided symlinks before reporting.
