### ISSUE TITLE
new structure instrumentation and logger (Heimdall)

### ISSUE THREAD

**Issue by stefanpenner** [broccolijs/broccoli#307]
Our WIP friendly fork over at ember-cli https://github.com/ember-cli/broccoli/pull/4 has added structured logging and instrumentation via heimdalljs.

I am opening this issue, so we remember this was another deviation.

I still hope to find some time to get to re-combine the fork. But iterating independently has let us address our issues quickly, and hopefully learn lessons the mainline can benefit from.

**Comment by hjdivad** [comment]
about to fork sane-watcher, another part of this fork

**Comment by joliss** [comment]
I was about to rewrite broccoli-sane-watcher to conform to the Broccoli 1.0 API. (It doesn't work with Broccoli 1.0 beta yet.) Should I coordinate with someone? I'm not completely sure what's going on.

**Comment by hjdivad** [comment]
@joliss I don't think it will matter for broccoli-sane-watcher.  Our changes there are minimal, and porting them to a 1.0 compliant broccoli-sane-watcher shouldn't be much effort for us.

The bigger effort is upgrading ember-cli & friends to be 1.0 compliant.

Our changes to broccoli-sane-watcher amount to:

 - Assume that we can pull a heimdalljs node off of a broccoli node (this is done by ember-cli/broccoli)
 - Update broccoli-slow-trees to '^3.0.0' so we get slow-trees output from heimdall nodes (rather than broccoli nodes).

Having said that I'd love to catch you up on the work @stefanpenner and I are doing and get your thoughts.  Happy to chat over slack, hangouts &c. whatever's convenient.

**Comment by hjdivad** [comment]
The tl;dr is making it easier to do performance analysis work

- get a common format for instrumentation information, for times & counts
- a js lib to make it easy to produce the format with PAYGO performance
- visualization and query tools to make it easier to explore this data


- https://github.com/heimdalljs/heimdalljs-lib

as a side bonus we have some configurable (not from CLI yet) context-aware logging that reports the path tail (across the broccoli tree ) when logging.  https://github.com/heimdalljs/heimdalljs-logger

So you'll get log entries like
```
// not a real log line, but more or less representative
fs-tree-diff: [TreeMerger(babel):2 -> Funnel:3 -> applyPatches:4] ...
```

**Comment by stefanpenner** [comment]
complete
