### ISSUE TITLE
broccolijs.com speaks of node 0.10.x as the latest stable version of node

### ISSUE THREAD

**Issue by chris-morgan** [broccolijs/broccoli#343]
From http://broccolijs.com/:

> If you don't currently have it installed, you'll need to get the latest stable version of node (v0.10.x). We recommend using [NVM](https://github.com/creationix/nvm). Test to make sure you have node and npm installed by running the following commands and checking that your output is similar:
>
> ```
> ~ $  node --version
> v0.10.x
> ~ $  npm --version
> 1.4.x
> ```

Node v0.10.x hasn’t been the latest stable version of Node for 2¾ years.

Seeing this made me initially assume that Broccoli was unsupported—not the impression I imagine you want to make.

**Comment by rwjblue** [comment]
Thank you for reporting!!! We need to track down which repo is used to deploy there (I’m not 100% who set it up), and get it updated. 

@stefanpenner / @joliss - do y’all know who set it up (and which repo)?

**Comment by stefanpenner** [comment]
no clue

**Comment by stefanpenner** [comment]
@joliss I would gladly take over on-going maintenance of broccolijs.com site/domain.

**Comment by stefanpenner** [comment]
Looks like the site is also having some DNS troubles. (for me)

**Comment by tsing80** [comment]
#222 ?

**Comment by stefanpenner** [comment]
@tsing80 thats old, the issue was resolved since then. Looks like a new issue cropped up.

**Comment by folz** [comment]
Although I turned over the domain to Jo, the registrar still points to my old DNS (which is hosting https://github.com/folz/broccoli-site - the repo you're looking for, although I recommend you don't try to reuse it). You would need her to update her registrar's DNS settings.

Also, I wanted to let you know that I'll soon be closing down the account which hosts the old website. Since broccolijs.com still points there, it will stop resolving once I close my account. What's a good timeline to give you all the time needed to set up a new site?

**Comment by oligriffiths** [comment]
THe current minimum supported node version is 8.
Closing this issue now, please reopen if this is still a problem.
